<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
 /**
* Run the database seeds.
*
* @return void
*/
 public function run()
 {

    $countries = [
        array('id' => '1','name_ar' => 'أندورا', 'name_en' => 'Andorra',),
        array('id' => '2','name_ar' => 'الإمارات العربية المتحدة','name_en' => 'United Arab Emirates'),
        array('id' => '3','name_ar' => 'أفغانستان','name_en' => 'Afghanistan'),
        array('id' => '4','name_ar' => 'أنتيغوا وبربودا','name_en' => 'Antigua and Barbuda'),
        array('id' => '5','name_ar' => 'أنغيلا', 'name_en' => 'Anguilla'),
        array('id' => '6','name_ar' => 'ألبانيا','name_en' => 'Albania'),
        array('id' => '7','name_ar' => 'أرمينيا','name_en' => 'Armenia'),
        array('id' => '8','name_ar' => 'جزر الأنتيل الهولندية','name_en' => 'Netherlands Antilles'),
        array('id' => '9','name_ar' => 'أنغولا','name_en' => 'Angola'),
        array('id' => '10','name_ar' => 'الأرجنتين','name_en' => 'Argentina'),
        array('id' => '11','name_ar' => 'النمسا','name_en' => 'Austria'),
        array('id' => '12','name_ar' => 'أستراليا','name_en' => 'Australia'),
        array('id' => '13','name_ar' => 'أروبا', 'name_en' => 'Aruba'),
        array('id' => '14','name_ar' => 'أذربيجان','name_en' => 'Azerbaijan'),
        array('id' => '15','name_ar' => 'البوسنة والهرسك','name_en' => 'Bosnia and Herzegovina'),
        array('id' => '16','name_ar' => 'بربادوس','name_en' => 'Barbados'),
        array('id' => '17','name_ar' => 'بنغلاديش','name_en' => 'Bangladesh'),
        array('id' => '18','name_ar' => 'بلجيكا', 'name_en' => 'Belgium'),
        array('id' => '19','name_ar' => 'بوركينا فاسو','name_en' => 'Burkina Faso'),
        array('id' => '20','name_ar' => 'بلغاريا', 'name_en' => 'Bulgaria'),
        array('id' => '21','name_ar' => 'البحرين','name_en' => 'Bahrain'),
        array('id' => '22','name_ar' => 'بوروندي','name_en' => 'Burundi'),
        array('id' => '23','name_ar' => 'بنين', 'name_en' => 'Benin'),
        array('id' => '24','name_ar' => 'برمودا', 'name_en' => 'Bermuda'),
        array('id' => '25','name_ar' => 'بروناي دار السلام','name_en' => 'Brunei Darussalam'),
        array('id' => '26','name_ar' => 'بوليفيا','name_en' => 'Bolivia'),
        array('id' => '27','name_ar' => 'البرازيل','name_en' => 'Brazil'),
        array('id' => '28','name_ar' => 'الباهاما', 'name_en' => 'Bahamas'),
        array('id' => '29','name_ar' => 'بوتان', 'name_en' => 'Bhutan'),
        array('id' => '30','name_ar' => 'بوتسوانا','name_en' => 'Botswana'),
        array('id' => '31','name_ar' => 'روسيا البيضاء','name_en' => 'Belarus'),
        array('id' => '32','name_ar' => 'بليز','name_en' => 'Belize'),
        array('id' => '33','name_ar' => 'كندا','name_en' => 'Canada'),
        array('id' => '34','name_ar' => 'جزر كوكوس (كيلينغ)','name_en' => 'Cocos (Keeling) Islands'),
        array('id' => '35','name_ar' => 'جمهورية الكونغو الديموقراطية','name_en' => 'Democratic Republic of the Congo'),
        array('id' => '36','name_ar' => 'جمهورية افريقيا الوسطى','name_en' => 'Central African Republic'),
        array('id' => '37','name_ar' => 'الكونغو','name_en' => 'Congo'),
        array('id' => '38','name_ar' => 'سويسرا','name_en' => 'Switzerland'),
        array('id' => '39','name_ar' => 'ساحل العاج (ساحل العاج)','name_en' => 'Cote D\'Ivoire (Ivory Coast)'),
        array('id' => '40','name_ar' => 'جزر كوك','name_en' => 'Cook Islands'),
        array('id' => '41','name_ar' => 'تشيلي','name_en' => 'Chile'),
        array('id' => '42','name_ar' => 'الكاميرون','name_en' => 'Cameroon'),
        array('id' => '43','name_ar' => 'الصين','name_en' => 'China'),
        array('id' => '44','name_ar' => 'كولومبيا','name_en' => 'Colombia'),
        array('id' => '45','name_ar' => 'كوستا ريكا', 'name_en' => 'Costa Rica'),
        array('id' => '46','name_ar' => 'كوبا','name_en' => 'Cuba'),
        array('id' => '47','name_ar' => 'الرأس الأخضر','name_en' => 'Cape Verde'),
        array('id' => '48','name_ar' => 'جزيرة الكريسماس','name_en' => 'Christmas Island'),
        array('id' => '49','name_ar' => 'قبرص', 'name_en' => 'Cyprus'),
        array('id' => '50','name_ar' => 'جمهورية التشيك', 'name_en' => 'Czech Republic'),
        array('id' => '51','name_ar' => 'ألمانيا','name_en' => 'Germany'),
        array('id' => '52','name_ar' => 'جيبوتي','name_en' => 'Djibouti'),
        array('id' => '53','name_ar' => 'الدنمارك','name_en' => 'Denmark'),
        array('id' => '54','name_ar' => 'دومينيكا','name_en' => 'Dominica'),
        array('id' => '55','name_ar' => 'جمهورية الدومنيكان','name_en' => 'Dominican Republic'),
        array('id' => '56','name_ar' => 'الجزائر','name_en' => 'Algeria'),
        array('id' => '57','name_ar' => 'الإكوادور','name_en' => 'Ecuador'),
        array('id' => '58','name_ar' => 'استونيا','name_en' => 'Estonia'),
        array('id' => '59','name_ar' => 'مصر', 'name_en' => 'Egypt'),
        array('id' => '60','name_ar' => 'الصحراء الغربية','name_en' => 'Western Sahara'),
        array('id' => '61','name_ar' => 'إريتريا','name_en' => 'Eritrea'),
        array('id' => '62','name_ar' => 'إسبانيا','name_en' => 'Spain'),
        array('id' => '63','name_ar' => 'أثيوبيا','name_en' => 'Ethiopia'),
        array('id' => '64','name_ar' => 'فنلندا','name_en' => 'Finland'),
        array('id' => '65','name_ar' => 'فيجي','name_en' => 'Fiji'),
        array('id' => '66','name_ar' => 'جزر فوكلاند (مالفيناس)', 'name_en' => 'Falkland Islands (Malvinas)'),
        array('id' => '67','name_ar' => 'ولايات ميكرونيزيا الموحدة', 'name_en' => 'Federated States of Micronesia'),
        array('id' => '68','name_ar' => 'جزر صناعية','name_en' => 'Faroe Islands'),
        array('id' => '69','name_ar' => 'فرنسا', 'name_en' => 'France'),
        array('id' => '70','name_ar' => 'الغابون','name_en' => 'Gabon'),
        array('id' => '71','name_ar' => 'بريطانيا العظمى (المملكة المتحدة)', 'name_en' => 'Great Britain (UK)'),
        array('id' => '72','name_ar' => 'غرينادا','name_en' => 'Grenada'),
        array('id' => '73','name_ar' => 'جورجيا','name_en' => 'Georgia'),
        array('id' => '74','name_ar' => 'غيانا الفرنسية','name_en' => 'French Guiana'),
        array('id' => '75','name_ar' => 'لا شيء','name_en' => 'NULL'),
        array('id' => '76','name_ar' => 'غانا','name_en' => 'Ghana'),
        array('id' => '77','name_ar' => 'جبل طارق', 'name_en' => 'Gibraltar'),
        array('id' => '78','name_ar' => 'الأرض الخضراء', 'name_en' => 'Greenland'),
        array('id' => '79','name_ar' => 'غامبيا', 'name_en' => 'Gambia'),
        array('id' => '80','name_ar' => 'غينيا', 'name_en' => 'Guinea'),
        array('id' => '81','name_ar' => 'جوادلوب','name_en' => 'Guadeloupe'),
        array('id' => '82','name_ar' => 'غينيا الإستوائية','name_en' => 'Equatorial Guinea'),
        array('id' => '83','name_ar' => 'اليونان','name_en' => 'Greece'),
        array('id' => '84','name_ar' => 'جورجيا وجزر ساندويتش','name_en' => 'S. Georgia and S. Sandwich Islands'),
        array('id' => '85','name_ar' => 'غواتيمالا', 'name_en' => 'Guatemala'),
        array('id' => '86','name_ar' => 'غينيا بيساو', 'name_en' => 'Guinea-Bissau'),
        array('id' => '87','name_ar' => 'غيانا', 'name_en' => 'Guyana'),
        array('id' => '88','name_ar' => 'هونغ كونغ', 'name_en' => 'Hong Kong'),
        array('id' => '89','name_ar' => 'هندوراس','name_en' => 'Honduras'),
        array('id' => '90','name_ar' => 'كرواتيا (هرفاتسكا)','name_en' => 'Croatia (Hrvatska)'),
        array('id' => '91','name_ar' => 'هايتي','name_en' => 'Haiti'),
        array('id' => '92','name_ar' => 'اليونان','name_en' => 'Hungary'),
        array('id' => '93','name_ar' => 'أندونيسيا', 'name_en' => 'Indonesia'),
        array('id' => '94','name_ar' => 'أيرلندا','name_en' => 'Ireland'),
        array('id' => '96','name_ar' => 'الهند','name_en' => 'India'),
        array('id' => '97','name_ar' => 'العراق','name_en' => 'Iraq'),
        array('id' => '98','name_ar' => 'إيران','name_en' => 'Iran'),
        array('id' => '99','name_ar' => 'أيسلندا','name_en' => 'Iceland'),
        array('id' => '100','name_ar' => 'إيطاليا', 'name_en' => 'Italy'),
        array('id' => '101','name_ar' => 'جامايكا','name_en' => 'Jamaica'),
        array('id' => '102','name_ar' => 'الأردن', 'name_en' => 'Jordan'),
        array('id' => '103','name_ar' => 'اليابان','name_en' => 'Japan'),
        array('id' => '104','name_ar' => 'كينيا','name_en' => 'Kenya'),
        array('id' => '105','name_ar' => 'قرغيزستان','name_en' => 'Kyrgyzstan'),
        array('id' => '106','name_ar' => 'كمبوديا','name_en' => 'Cambodia'),
        array('id' => '107','name_ar' => 'كيريباس','name_en' => 'Kiribati'),
        array('id' => '108','name_ar' => 'جزر القمر','name_en' => 'Comoros'),
        array('id' => '109','name_ar' => 'سانت كيتس ونيفيس','name_en' => 'Saint Kitts and Nevis'),
        array('id' => '110','name_ar' => 'كوريا الشمالية', 'name_en' => 'Korea (North)'),
        array('id' => '111','name_ar' => 'كوريا، جنوب)', 'name_en' => 'Korea (South)'),
        array('id' => '112','name_ar' => 'الكويت', 'name_en' => 'Kuwait'),
        array('id' => '113','name_ar' => 'جزر كايمان','name_en' => 'Cayman Islands'),
        array('id' => '114','name_ar' => 'كازاخستان', 'name_en' => 'Kazakhstan'),
        array('id' => '115','name_ar' => 'لاوس','name_en' => 'Laos'),
        array('id' => '116','name_ar' => 'لبنان','name_en' => 'Lebanon'),
        array('id' => '117','name_ar' => 'القديسة لوسيا','name_en' => 'Saint Lucia'),
        array('id' => '118','name_ar' => 'ليختنشتاين', 'name_en' => 'Liechtenstein'),
        array('id' => '119','name_ar' => 'سيريلانكا', 'name_en' => 'Sri Lanka'),
        array('id' => '120','name_ar' => 'ليبيريا','name_en' => 'Liberia'),
        array('id' => '121','name_ar' => 'ليسوتو','name_en' => 'Lesotho'),
        array('id' => '122','name_ar' => 'ليتوانيا','name_en' => 'Lithuania'),
        array('id' => '123','name_ar' => 'لوكسمبورغ','name_en' => 'Luxembourg'),
        array('id' => '124','name_ar' => 'لاتفيا','name_en' => 'Latvia'),
        array('id' => '125','name_ar' => 'ليبيا','name_en' => 'Libya'),
        array('id' => '126','name_ar' => 'المغرب','name_en' => 'Morocco'),
        array('id' => '127','name_ar' => 'موناكو', 'name_en' => 'Monaco'),
        array('id' => '128','name_ar' => 'مولدوفا','name_en' => 'Moldova'),
        array('id' => '129','name_ar' => 'مدغشقر','name_en' => 'Madagascar'),
        array('id' => '130','name_ar' => 'جزر مارشال', 'name_en' => 'Marshall Islands'),
        array('id' => '131','name_ar' => 'مقدونيا', 'name_en' => 'Macedonia'),
        array('id' => '132','name_ar' => 'مالي','name_en' => 'Mali'),
        array('id' => '133','name_ar' => 'ميانمار','name_en' => 'Myanmar'),
        array('id' => '134','name_ar' => 'منغوليا','name_en' => 'Mongolia'),
        array('id' => '135','name_ar' => 'ماكاو','name_en' => 'Macao'),
        array('id' => '136','name_ar' => 'جزر مريانا الشمالية','name_en' => 'Northern Mariana Islands'),
        array('id' => '137','name_ar' => 'مارتينيك','name_en' => 'Martinique'),
        array('id' => '138','name_ar' => 'موريتانيا','name_en' => 'Mauritania'),
        array('id' => '139','name_ar' => 'مونتسيرات','name_en' => 'Montserrat'),
        array('id' => '140','name_ar' => 'مالطا','name_en' => 'Malta'),
        array('id' => '141','name_ar' => 'موريشيوس','name_en' => 'Mauritius'),
        array('id' => '142','name_ar' => 'جزر المالديف','name_en' => 'Maldives'),
        array('id' => '143','name_ar' => 'مالاوي', 'name_en' => 'Malawi'),
        array('id' => '144','name_ar' => 'المكسيك','name_en' => 'Mexico'),
        array('id' => '145','name_ar' => 'ماليزيا','name_en' => 'Malaysia'),
        array('id' => '146','name_ar' => 'موزمبيق','name_en' => 'Mozambique'),
        array('id' => '147','name_ar' => 'ناميبيا','name_en' => 'Namibia'),
        array('id' => '148','name_ar' => 'كاليدونيا الجديدة','name_en' => 'New Caledonia'),
        array('id' => '149','name_ar' => 'النيجر','name_en' => 'Niger'),
        array('id' => '150','name_ar' => 'جزيرة نورفولك','name_en' => 'Norfolk Island'),
        array('id' => '151','name_ar' => 'نيجيريا','name_en' => 'Nigeria'),
        array('id' => '152','name_ar' => 'نيكاراغوا', 'name_en' => 'Nicaragua'),
        array('id' => '153','name_ar' => 'هولندا','name_en' => 'Netherlands'),
        array('id' => '154','name_ar' => 'النرويج','name_en' => 'Norway'),
        array('id' => '155','name_ar' => 'نيبال','name_en' => 'Nepal'),
        array('id' => '156','name_ar' => 'ناورو','name_en' => 'Nauru'),
        array('id' => '157','name_ar' => 'نيوي','name_en' => 'Niue'),
        array('id' => '158','name_ar' => 'نيوزيلندا (اوتياروا)', 'name_en' => 'New Zealand (Aotearoa)'),
        array('id' => '159','name_ar' => 'سلطنة عمان','name_en' => 'Oman'),
        array('id' => '160','name_ar' => 'بناما', 'name_en' => 'Panama'),
        array('id' => '161','name_ar' => 'بيرو','name_en' => 'Peru'),
        array('id' => '162','name_ar' => 'بولينيزيا الفرنسية', 'name_en' => 'French Polynesia'),
        array('id' => '163','name_ar' => 'بابوا غينيا الجديدة','name_en' => 'Papua New Guinea'),
        array('id' => '164','name_ar' => 'الفلبين','name_en' => 'Philippines'),
        array('id' => '165','name_ar' => 'باكستان','name_en' => 'Pakistan'),
        array('id' => '166','name_ar' => 'بولندا','name_en' => 'Poland'),
        array('id' => '167','name_ar' => 'سانت بيير وميكلون', 'name_en' => 'Saint Pierre and Miquelon'),
        array('id' => '168','name_ar' => 'بيتكيرن','name_en' => 'Pitcairn'),
        array('id' => '169','name_ar' => 'الأراضي الفلسطينية','name_en' => 'Palestinian Territory'),
        array('id' => '170','name_ar' => 'البرتغال','name_en' => 'Portugal'),
        array('id' => '171','name_ar' => 'بالاو','name_en' => 'Palau'),
        array('id' => '172','name_ar' => 'باراغواي','name_en' => 'Paraguay'),
        array('id' => '173','name_ar' => 'دولة قطر','name_en' => 'Qatar'),
        array('id' => '174','name_ar' => 'جمع شمل','name_en' => 'Reunion'),
        array('id' => '175','name_ar' => 'رومانيا','name_en' => 'Romania'),
        array('id' => '176','name_ar' => 'الاتحاد الروسي', 'name_en' => 'Russian Federation'),
        array('id' => '177','name_ar' => 'رواندا', 'name_en' => 'Rwanda'),
        array('id' => '178','name_ar' => 'المملكة العربية السعودية','name_en' => 'Saudi Arabia'),
        array('id' => '179','name_ar' => 'جزر سليمان', 'name_en' => 'Solomon Islands'),
        array('id' => '180','name_ar' => 'سيشيل','name_en' => 'Seychelles'),
        array('id' => '181','name_ar' => 'سودان', 'name_en' => 'Sudan'),
        array('id' => '182','name_ar' => 'السويد','name_en' => 'Sweden'),
        array('id' => '183','name_ar' => 'سنغافورة', 'name_en' => 'Singapore'),
        array('id' => '184','name_ar' => 'سانت هيلانة', 'name_en' => 'Saint Helena'),
        array('id' => '185','name_ar' => 'سلوفينيا','name_en' => 'Slovenia'),
        array('id' => '186','name_ar' => 'سفالبارد وجان مايان', 'name_en' => 'Svalbard and Jan Mayen'),
        array('id' => '187','name_ar' => 'سلوفاكيا','name_en' => 'Slovakia'),
        array('id' => '188','name_ar' => 'سيرا ليون','name_en' => 'Sierra Leone'),
        array('id' => '189','name_ar' => 'سان مارينو','name_en' => 'San Marino'),
        array('id' => '190','name_ar' => 'السنغال','name_en' => 'Senegal'),
        array('id' => '191','name_ar' => 'الصومال','name_en' => 'Somalia'),
        array('id' => '192','name_ar' => 'سورينام','name_en' => 'Suriname'),
        array('id' => '193','name_ar' => 'ساو تومي وبرنسيبي','name_en' => 'Sao Tome and Principe'),
        array('id' => '194','name_ar' => 'السلفادور','name_en' => 'El Salvador'),
        array('id' => '195','name_ar' => 'سوريا','name_en' => 'Syria'),
        array('id' => '196','name_ar' => 'سوازيلاند', 'name_en' => 'Swaziland'),
        array('id' => '197','name_ar' => 'جزر تركس وكايكوس','name_en' => 'Turks and Caicos Islands'),
        array('id' => '198','name_ar' => 'تشاد','name_en' => 'Chad'),
        array('id' => '199','name_ar' => 'المناطق الجنوبية لفرنسا','name_en' => 'French Southern Territories'),
        array('id' => '200','name_ar' => 'ليذهب','name_en' => 'Togo'),
        array('id' => '201','name_ar' => 'تايلاند', 'name_en' => 'Thailand'),
        array('id' => '202','name_ar' => 'طاجيكستان','name_en' => 'Tajikistan'),
        array('id' => '203','name_ar' => 'توكيلاو','name_en' => 'Tokelau'),
        array('id' => '204','name_ar' => 'تركمانستان','name_en' => 'Turkmenistan'),
        array('id' => '205','name_ar' => 'تونس','name_en' => 'Tunisia'),
        array('id' => '206','name_ar' => 'تونغا','name_en' => 'Tonga'),
        array('id' => '207','name_ar' => 'ديك رومي','name_en' => 'Turkey'),
        array('id' => '208','name_ar' => 'ترينداد وتوباغو','name_en' => 'Trinidad and Tobago'),
        array('id' => '209','name_ar' => 'توفالو', 'name_en' => 'Tuvalu'),
        array('id' => '210','name_ar' => 'تايوان', 'name_en' => 'Taiwan'),
        array('id' => '211','name_ar' => 'تنزانيا','name_en' => 'Tanzania'),
        array('id' => '212','name_ar' => 'أوكرانيا','name_en' => 'Ukraine'),
        array('id' => '213','name_ar' => 'أوغندا','name_en' => 'Uganda'),
        array('id' => '214','name_ar' => 'أوروغواي','name_en' => 'Uruguay'),
        array('id' => '215','name_ar' => 'أوزبكستان','name_en' => 'Uzbekistan'),
        array('id' => '216','name_ar' => 'سانت فنسنت وجزر غرينادين', 'name_en' => 'Saint Vincent and the Grenadines'),
        array('id' => '217','name_ar' => 'فنزويلا', 'name_en' => 'Venezuela'),
        array('id' => '218','name_ar' => 'جزر العذراء البريطانية)','name_en' => 'Virgin Islands (British)'),
        array('id' => '219','name_ar' => 'جزر فيرجن (الولايات المتحدة)', 'name_en' => 'Virgin Islands (U.S.)'),
        array('id' => '220','name_ar' => 'فيتنام','name_en' => 'Viet Nam'),
        array('id' => '221','name_ar' => 'فانواتو','name_en' => 'Vanuatu'),
        array('id' => '222','name_ar' => 'واليس وفوتونا', 'name_en' => 'Wallis and Futuna'),
        array('id' => '223','name_ar' => 'ساموا','name_en' => 'Samoa'),
        array('id' => '224','name_ar' => 'اليمن','name_en' => 'Yemen'),
        array('id' => '225','name_ar' => 'مايوت','name_en' => 'Mayotte'),
        array('id' => '226','name_ar' => 'جنوب أفريقيا','name_en' => 'South Africa'),
        array('id' => '227','name_ar' => 'زامبيا', 'name_en' => 'Zambia'),
        array('id' => '228','name_ar' => 'زائير (سابقة)','name_en' => 'Zaire (former)'),
        array('id' => '229','name_ar' => 'زيمبابوي','name_en' => 'Zimbabwe'),
        array('id' => '230','name_ar' => 'الولايات المتحدة','name_en' => 'United States of America'),
        array('id' => '231','name_ar' => 'غير معروف','name_en' => 'unknown')
    ];

DB::table('countries')->insert($countries);
}
}
